networks:
  workshop-client.network:
    driver: bridge

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/app.dev
    tty: true
    networks:
      - workshop-client.network
    ports:
      - "9095:9000" # PHP-FPM
      - "9093:9003" # Xdebug

  apache:
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/app.dev
    networks:
      - workshop-client.network
    depends_on:
      - php

  postgres:
    image: postgres:17-alpine3.21
    volumes:
      - workshop-client-postgres-db:/var/lib/postgresql/data
    tty: true
    restart: always
    networks:
      - workshop-client.network
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  workshop-client-code:
  workshop-client-postgres-db:
    driver: local
